### PR TITLE
update plugin to use proper logging framework

### PR DESCRIPTION
**Pull request by jaredstehler**

### CODE REVIEW

**Comment by noly** [comment]
Thanks @jaredstehler for submitting this change 😀 

currently your changes are failing in our pipeline when building the debug image due a missing `logrus` package, I'm taking a look; here more details if you are curious:

Screen Shot 2021-09-07 at 17 08 04

**Review by noly — CHANGES_REQUESTED** [review]
You would need to update Dockerfile_debug and Dockerfile_firelens image with 
```
RUN go get github.com/sirupsen/logrus
```

**Review by noly — DISMISSED** [review]

**Comment by noly** [comment]
Awesome @jaredstehler, one thing I forgot to mention yesterday, We upgrade the version number manually in the [version.go](https://github.com/newrelic/newrelic-fluent-bit-output/blob/master/version.go) file.

Once You update it and sign the contributor license agreement we can merge it to master.

**Comment by jaredstehler** [comment]
@noly should be ready for review

**Review by noly — APPROVED** [review]
Awesome!! Thanks for your contribution @jaredstehler

**Pull request merged**
